### ISSUE TITLE
Feature: Add Help and Support page

### ISSUE THREAD

**Issue by SauravMukherjee44** [SauravMukherjee44/Aec-Library-Website#1159] opened 2023-05-22 16:46 UTC
### Feature description

Design the help and support page.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by saiwali** [comment] 2023-05-22 17:22
Hello, @SauravMukherjee44 I would like to contribute to this issue. Can you assign this issue to me?

**Comment by Divyanshu975** [comment] 2023-05-22 17:38
Hey I would like to help resolve this issue, could you please assign this issue to me under GSSOC'23?

**Comment by Hritik1503** [comment] 2023-05-23 01:22
I am interested to work on this issue please assign me this task under GSSOC.

**Comment by SauravMukherjee44** [comment] 2023-05-23 11:49
@saiwali You can go for it.
For any help, you can reach out to me here: https://sauravmukherjee.bio.link/

**Closed** 2023-05-23 16:47 UTC
Labels: Level2, gssoc23

**Comment by saiwali** [comment] 2023-05-24 18:17
Hello, @SauravMukherjee44 I am new to Open Source and just had a question that I didn't even start contributing and the issue is closed. So will my further contributions be valid?
